import type { BrandData } from "@/lib/types";

export function buildBrandGuidelinesContent(brandName: string, brandData: BrandData): string {
  return `
# ${brandName} Brand Guidelines

## Brand Overview
${brandName} is a ${brandData.style} brand in the ${brandData.industry} sector,
targeting ${brandData.targetAudience}.

## Brand Personality
${brandData.personality.map(p => `- ${p}`).join('\n')}

## Color System
### Primary Colors
${brandData.primaryColors.map(c => `- ${c.name}: ${c.hex} — ${c.usage}`).join('\n')}

### Secondary Colors
${brandData.secondaryColors.map(c => `- ${c.name}: ${c.hex} — ${c.usage}`).join('\n')}

### Accent Colors
${brandData.accentColors.map(c => `- ${c.name}: ${c.hex} — ${c.usage}`).join('\n')}

## Typography
${brandData.fontPairings.map(f => `
### ${f.mood} Pairing
- Heading: ${f.heading}
- Body: ${f.body}
`).join('\n')}

## Brand Voice
${brandData.brandVoice.tone}

### Vocabulary
${brandData.brandVoice.vocabulary.map(v => `- ${v}`).join('\n')}

## Design Principles
${brandData.designPrinciples.map((p, i) => `${i + 1}. ${p}`).join('\n')}

## Tagline Options
${brandData.taglineSuggestions.map(t => `- "${t}"`).join('\n')}

---
*Generated by CreaCurve — creacurve.com*
`.trim();
}
