/**
 * Brand guidelines PDF for the logo-prep tool.
 * US Letter portrait — 8.5 × 11 inches (612 × 792pt at 72dpi).
 */

import PDFDocument from "pdfkit";
import type { BrandColor } from "@/lib/types";

// ── Page dimensions ────────────────────────────────────────────────────────────
const PW = 612;   // 8.5 in × 72
const PH = 792;   // 11 in × 72
const MG = 48;
const CW = PW - MG * 2;

// ── Colour helpers ─────────────────────────────────────────────────────────────
function hexToRgb(hex: string) {
  const h = hex.replace("#", "");
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16),
  };
}

function rgbToCmyk(r: number, g: number, b: number) {
  const r1 = r / 255, g1 = g / 255, b1 = b / 255;
  const k = 1 - Math.max(r1, g1, b1);
  if (k === 1) return { c: 0, m: 0, y: 0, k: 100 };
  const d = 1 - k;
  return {
    c: Math.round(((1 - r1 - k) / d) * 100),
    m: Math.round(((1 - g1 - k) / d) * 100),
    y: Math.round(((1 - b1 - k) / d) * 100),
    k: Math.round(k * 100),
  };
}

function isLight(hex: string) {
  const { r, g, b } = hexToRgb(hex);
  return (r * 299 + g * 587 + b * 114) / 1000 > 155;
}

// ── Shared helpers ─────────────────────────────────────────────────────────────
function sectionHeader(doc: PDFKit.PDFDocument, title: string, y: number, accent: string) {
  const { r, g, b } = hexToRgb(accent);
  doc.rect(MG, y, CW, 2).fill([r, g, b]);
  doc.font("Helvetica-Bold").fontSize(9).fillColor("#999999")
    .text(title.toUpperCase(), MG, y + 8, { characterSpacing: 1.5 });
  return y + 26;
}

function footer(doc: PDFKit.PDFDocument, pageNum: number, brandName: string) {
  doc.font("Helvetica").fontSize(7).fillColor("#bbbbbb")
    .text(`${brandName} Brand Guidelines`, MG, PH - 28, { width: CW / 2 })
    .text(`${pageNum}`, MG + CW / 2, PH - 28, { width: CW / 2, align: "right" });
}

// ── Page 1 — Cover ─────────────────────────────────────────────────────────────
function pageCover(
  doc: PDFKit.PDFDocument,
  brandName: string,
  logoBuf: Buffer | null,
  accent: string,
) {
  const { r, g, b } = hexToRgb(accent);

  // Accent band top
  doc.rect(0, 0, PW, 6).fill([r, g, b]);

  // Large brand-name block
  doc.rect(0, 6, PW, PH * 0.55).fill("#f7f7f9");

  // Logo centred in upper half
  if (logoBuf) {
    try {
      const logoSize = 140;
      doc.image(logoBuf, (PW - logoSize) / 2, 60, { fit: [logoSize, logoSize], align: "center" });
    } catch { /* skip */ }
  }

  // Brand name
  doc.font("Helvetica-Bold").fontSize(34).fillColor("#111111")
    .text(brandName, MG, PH * 0.55 + 40, { align: "center", width: CW });

  doc.rect(PW / 2 - 28, PH * 0.55 + 84, 56, 2).fill([r, g, b]);

  doc.font("Helvetica").fontSize(11).fillColor("#888888")
    .text("Brand Identity Guidelines", MG, PH * 0.55 + 96, { align: "center", width: CW });

  doc.font("Helvetica").fontSize(8).fillColor("#bbbbbb")
    .text(`Generated by CreaCurve — creacurve.com`, MG, PH - 36, { align: "center", width: CW });

  // Accent band bottom
  doc.rect(0, PH - 6, PW, 6).fill([r, g, b]);
}

// ── Page 2 — The Logo ──────────────────────────────────────────────────────────
function pageLogo(
  doc: PDFKit.PDFDocument,
  brandName: string,
  logoBuf: Buffer | null,
  accent: string,
) {
  doc.rect(0, 0, PW, 6).fill(hexToRgb(accent) as unknown as string);

  let y = MG;
  y = sectionHeader(doc, "The Logo", y, accent);

  doc.font("Helvetica-Bold").fontSize(18).fillColor("#111111")
    .text("Primary Logo", MG, y);
  y += 28;

  // Checkerboard-style light bg for logo display
  const boxH = 180;
  doc.rect(MG, y, CW, boxH).fill("#f0f0f2");
  if (logoBuf) {
    try {
      doc.image(logoBuf, MG + CW / 2 - 75, y + (boxH - 120) / 2, { fit: [150, 120], align: "center" });
    } catch { /* skip */ }
  }
  y += boxH + 20;

  doc.font("Helvetica").fontSize(10).fillColor("#555555")
    .text(
      `The ${brandName} logo is the primary visual asset of the brand. Always use the approved logo files and never alter its proportions, colors, or spacing.`,
      MG, y, { width: CW, lineGap: 4 },
    );
  y += 60;

  // Logo on white
  const halfW = (CW - 12) / 2;
  doc.rect(MG, y, halfW, 100).fill("#ffffff").rect(MG, y, halfW, 100).stroke("#e5e5e5");
  if (logoBuf) {
    try { doc.image(logoBuf, MG + 10, y + 18, { fit: [halfW - 20, 64] }); } catch { /* skip */ }
  }
  doc.font("Helvetica").fontSize(8).fillColor("#999999")
    .text("On light background", MG, y + 106, { width: halfW, align: "center" });

  // Logo on dark
  const x2 = MG + halfW + 12;
  const { r, g, b } = hexToRgb(accent);
  doc.rect(x2, y, halfW, 100).fill([r, g, b]);
  if (logoBuf) {
    try { doc.image(logoBuf, x2 + 10, y + 18, { fit: [halfW - 20, 64] }); } catch { /* skip */ }
  }
  doc.font("Helvetica").fontSize(8).fillColor("#ffffff")
    .text("On brand color", x2, y + 76, { width: halfW, align: "center" });

  footer(doc, 2, brandName);
}

// ── Page 3 — Color Palette ─────────────────────────────────────────────────────
function pageColors(
  doc: PDFKit.PDFDocument,
  brandName: string,
  colors: BrandColor[],
  accent: string,
) {
  doc.rect(0, 0, PW, 6).fill(hexToRgb(accent) as unknown as string);

  let y = MG;
  y = sectionHeader(doc, "Color Palette", y, accent);

  doc.font("Helvetica-Bold").fontSize(18).fillColor("#111111").text("Brand Colors", MG, y);
  y += 32;

  const swatchW = Math.min(100, Math.floor(CW / Math.min(colors.length, 6)) - 10);
  const swatchH = 80;
  const gap = 12;

  colors.slice(0, 6).forEach((c, i) => {
    const x = MG + i * (swatchW + gap);
    const { r, g, b } = c.rgb;
    const cmyk = rgbToCmyk(r, g, b);
    const textColor = isLight(c.hex) ? "#333333" : "#ffffff";

    // Swatch
    doc.rect(x, y, swatchW, swatchH).fill([r, g, b]);

    // Label overlay for color name
    doc.font("Helvetica-Bold").fontSize(7).fillColor(textColor)
      .text(c.name, x + 6, y + swatchH - 20, { width: swatchW - 12 });

    // Colour codes below swatch
    const ly = y + swatchH + 8;
    doc.font("Helvetica-Bold").fontSize(8).fillColor("#111111").text(c.hex.toUpperCase(), x, ly);
    doc.font("Helvetica").fontSize(7).fillColor("#666666")
      .text(`RGB ${r}, ${g}, ${b}`, x, ly + 12)
      .text(`CMYK ${cmyk.c} ${cmyk.m} ${cmyk.y} ${cmyk.k}`, x, ly + 22);

    // Usage tag
    doc.font("Helvetica").fontSize(7).fillColor("#999999").text(c.usage, x, ly + 36);
  });

  y += swatchH + 80;

  // Color usage rules
  y = sectionHeader(doc, "Color Usage", y, accent);
  doc.font("Helvetica").fontSize(10).fillColor("#555555")
    .text(
      "The primary brand color should be used for key UI elements, CTAs, and prominent headings. Secondary colors support and complement the primary. Avoid using more than three brand colors in a single composition.",
      MG, y, { width: CW, lineGap: 4 },
    );

  footer(doc, 3, brandName);
}

// ── Page 4 — Typography ────────────────────────────────────────────────────────
function pageTypography(
  doc: PDFKit.PDFDocument,
  brandName: string,
  accent: string,
) {
  doc.rect(0, 0, PW, 6).fill(hexToRgb(accent) as unknown as string);

  let y = MG;
  y = sectionHeader(doc, "Typography", y, accent);

  doc.font("Helvetica-Bold").fontSize(18).fillColor("#111111").text("Type System", MG, y);
  y += 32;

  // Primary font
  y = sectionHeader(doc, "Primary Typeface", y, accent);
  doc.font("Helvetica-Bold").fontSize(36).fillColor("#111111").text("Aa Bb Cc", MG, y);
  y += 52;
  doc.font("Helvetica-Bold").fontSize(10).fillColor("#111111").text("Helvetica / Arial", MG, y);
  doc.font("Helvetica").fontSize(9).fillColor("#777777").text("Headings, display text, brand mark", MG, y + 14);
  y += 44;

  // Type scale
  y = sectionHeader(doc, "Type Scale", y, accent);

  const scale = [
    { label: "H1 — Display",  size: 28, weight: "Helvetica-Bold"  },
    { label: "H2 — Title",    size: 20, weight: "Helvetica-Bold"  },
    { label: "H3 — Subtitle", size: 15, weight: "Helvetica-Bold"  },
    { label: "Body",          size: 11, weight: "Helvetica"       },
    { label: "Caption",       size:  9, weight: "Helvetica"       },
  ];

  scale.forEach(({ label, size, weight }) => {
    doc.font("Helvetica").fontSize(8).fillColor("#aaaaaa").text(label, MG, y, { continued: false });
    doc.font(weight).fontSize(size).fillColor("#111111").text(brandName, MG + 130, y - 2);
    y += Math.max(size + 10, 22);
  });

  y += 10;
  y = sectionHeader(doc, "Usage Rules", y, accent);
  doc.font("Helvetica").fontSize(10).fillColor("#555555")
    .text(
      "Use bold weight for headings and key callouts. Use regular weight for body text and captions. Maintain a consistent type scale across all brand touchpoints. Minimum body text size is 9pt for print.",
      MG, y, { width: CW, lineGap: 4 },
    );

  footer(doc, 4, brandName);
}

// ── Page 5 — Logo Usage / Dos & Don'ts ────────────────────────────────────────
function pageUsage(
  doc: PDFKit.PDFDocument,
  brandName: string,
  accent: string,
) {
  doc.rect(0, 0, PW, 6).fill(hexToRgb(accent) as unknown as string);

  let y = MG;
  y = sectionHeader(doc, "Logo Usage", y, accent);

  doc.font("Helvetica-Bold").fontSize(18).fillColor("#111111").text("Dos & Don'ts", MG, y);
  y += 32;

  const dos = [
    "Always use approved logo files",
    "Maintain minimum clear space equal to the height of the lettermark",
    "Use the full-color version on white and light backgrounds",
    "Use the white version on dark or brand-color backgrounds",
    "Scale proportionally — never stretch or squash",
  ];

  const donts = [
    "Don't alter the logo's colors",
    "Don't add drop shadows, outlines, or effects",
    "Don't rotate or skew the logo",
    "Don't place on busy or low-contrast backgrounds",
    "Don't use the logo smaller than 16px on screen",
  ];

  const colW = (CW - 16) / 2;

  // DO column
  const { r: ar, g: ag, b: ab } = hexToRgb(accent);
  doc.rect(MG, y, colW, 18).fill([ar, ag, ab]);
  doc.font("Helvetica-Bold").fontSize(9).fillColor(isLight(accent) ? "#111111" : "#ffffff")
    .text("✓  DO", MG + 8, y + 5);
  y += 24;

  dos.forEach((item) => {
    doc.rect(MG, y, 4, 4).fill([ar, ag, ab]);
    doc.font("Helvetica").fontSize(9).fillColor("#333333")
      .text(item, MG + 10, y - 1, { width: colW - 14 });
    y += 20;
  });

  // DON'T column
  const x2 = MG + colW + 16;
  let y2 = MG + 32;
  doc.rect(x2, y2, colW, 18).fill("#ef4444");
  doc.font("Helvetica-Bold").fontSize(9).fillColor("#ffffff").text("✗  DON'T", x2 + 8, y2 + 5);
  y2 += 24;

  donts.forEach((item) => {
    doc.rect(x2, y2, 4, 4).fill("#ef4444");
    doc.font("Helvetica").fontSize(9).fillColor("#333333")
      .text(item, x2 + 10, y2 - 1, { width: colW - 14 });
    y2 += 20;
  });

  y = Math.max(y, y2) + 24;
  y = sectionHeader(doc, "Clear Space", y, accent);
  doc.font("Helvetica").fontSize(10).fillColor("#555555")
    .text(
      `Always maintain a minimum clear space around the ${brandName} logo. This space should be equal to the cap height of the wordmark (or the logo unit height for icon-only versions). No other graphic elements, text, or imagery should appear within this zone.`,
      MG, y, { width: CW, lineGap: 4 },
    );

  footer(doc, 5, brandName);
}

// ── Main export ────────────────────────────────────────────────────────────────
export async function buildLogoPrepPDF(opts: {
  brandName: string;
  colors: BrandColor[];
  logoBuf: Buffer | null;
}): Promise<Buffer> {
  const { brandName, colors, logoBuf } = opts;
  const accent = colors[0]?.hex || "#7c3aed";

  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];

    const doc = new PDFDocument({
      size: [PW, PH],
      margin: 0,
      info: {
        Title:   `${brandName} — Brand Guidelines`,
        Author:  "CreaCurve",
        Subject: "Brand Identity Manual",
      },
    });

    doc.on("data",  (c: Buffer) => chunks.push(c));
    doc.on("end",   () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    pageCover(doc, brandName, logoBuf, accent);

    doc.addPage({ size: [PW, PH], margin: 0 });
    pageLogo(doc, brandName, logoBuf, accent);

    doc.addPage({ size: [PW, PH], margin: 0 });
    pageColors(doc, brandName, colors, accent);

    doc.addPage({ size: [PW, PH], margin: 0 });
    pageTypography(doc, brandName, accent);

    doc.addPage({ size: [PW, PH], margin: 0 });
    pageUsage(doc, brandName, accent);

    doc.end();
  });
}
