/**
 * Export the logo in print/design formats:
 *  • PDF  — 2-page (white bg + dark bg), US Letter, logo centered
 *  • SVG  — embedded raster in vector container (Illustrator/Inkscape compatible)
 *  • PSD  — flat RGBA Photoshop document written from raw pixel data
 *  • AI   — PDF 1.4 wrapper with Adobe Illustrator metadata header
 */

import PDFDocument from "pdfkit";
import sharp from "sharp";

/* ── shared ─────────────────────────────────────────────────────────────── */

const PW = 612;   // US Letter width  (8.5 in × 72)
const PH = 792;   // US Letter height (11 in × 72)
const PADDING = 80;

/* ── PDF ─────────────────────────────────────────────────────────────────── */

export async function buildLogoPDF(
  logoBuf: Buffer,
  brandName: string,
): Promise<Buffer> {
  // Resize to fit page content area at high quality
  const maxW = PW - PADDING * 2;
  const maxH = PH - PADDING * 2 - 60; // leave room for brand name
  const sized = await sharp(logoBuf)
    .resize(maxW, maxH, { fit: "inside", withoutEnlargement: false })
    .flatten({ background: { r: 255, g: 255, b: 255 } })
    .png()
    .toBuffer();

  // Dark bg version
  const sizedDark = await sharp(logoBuf)
    .resize(maxW, maxH, { fit: "inside", withoutEnlargement: false })
    .flatten({ background: { r: 14, g: 14, b: 24 } })
    .png()
    .toBuffer();

  const lMeta = await sharp(sized).metadata();
  const lW = lMeta.width!, lH = lMeta.height!;
  const logoX = Math.round((PW - lW) / 2);
  const logoY = Math.round((PH - lH) / 2) - 20;

  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({
      size: [PW, PH],
      margin: 0,
      info: { Title: `${brandName} Logo`, Author: "CreaCurve", Subject: "Logo Export" },
    });
    doc.on("data",  (c: Buffer) => chunks.push(c));
    doc.on("end",   () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // ── Page 1: white background ──
    doc.rect(0, 0, PW, PH).fill("#ffffff");
    try { doc.image(sized, logoX, logoY, { width: lW, height: lH }); } catch { /* skip */ }
    doc.font("Helvetica").fontSize(10).fillColor("#aaaaaa")
      .text(brandName, 0, PH - 48, { align: "center", width: PW });
    doc.font("Helvetica").fontSize(7).fillColor("#cccccc")
      .text("Generated by CreaCurve — creacurve.com", 0, PH - 32, { align: "center", width: PW });

    // ── Page 2: dark background ──
    doc.addPage({ size: [PW, PH], margin: 0 });
    doc.rect(0, 0, PW, PH).fill("#0e0e18");
    try { doc.image(sizedDark, logoX, logoY, { width: lW, height: lH }); } catch { /* skip */ }
    doc.font("Helvetica").fontSize(10).fillColor("#555577")
      .text(brandName, 0, PH - 48, { align: "center", width: PW });

    doc.end();
  });
}

/* ── SVG ─────────────────────────────────────────────────────────────────── */
// Embeds the logo as a base64 raster inside a proper SVG document.
// Opens in Illustrator (File → Place), Inkscape, browsers, and design tools.

export async function buildLogoSVG(logoBuf: Buffer): Promise<Buffer> {
  const meta   = await sharp(logoBuf).metadata();
  const w      = meta.width  || 800;
  const h      = meta.height || 600;
  const b64    = logoBuf.toString("base64");
  const mime   = "image/png";

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     version="1.1"
     width="${w}" height="${h}"
     viewBox="0 0 ${w} ${h}"
     xml:space="preserve">
  <title>Logo</title>
  <desc>Generated by CreaCurve — creacurve.com</desc>
  <image x="0" y="0" width="${w}" height="${h}"
         xlink:href="data:${mime};base64,${b64}"
         image-rendering="optimizeQuality"/>
</svg>`;

  return Buffer.from(svg, "utf-8");
}

/* ── PSD binary writer ───────────────────────────────────────────────────── */
// Produces a valid flat (merged) Photoshop PSD file from RGBA pixel data.
// Spec: https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/

function writeUInt16BE(buf: Buffer, value: number, offset: number) {
  buf[offset]     = (value >> 8) & 0xff;
  buf[offset + 1] = value & 0xff;
}
function writeUInt32BE(buf: Buffer, value: number, offset: number) {
  buf[offset]     = (value >> 24) & 0xff;
  buf[offset + 1] = (value >> 16) & 0xff;
  buf[offset + 2] = (value >>  8) & 0xff;
  buf[offset + 3] = value & 0xff;
}

/** PackBits RLE encode a single row of bytes (standard PSD compression) */
function packBitsRow(row: Buffer): Buffer {
  const out: number[] = [];
  let i = 0;
  while (i < row.length) {
    let j = i + 1;
    // Find run of identical bytes
    while (j < row.length && j - i < 128 && row[j] === row[i]) j++;
    if (j - i > 1) {
      // Run: repeat byte (j-i) times → write (-(j-i-1)), byte
      out.push(((-(j - i - 1)) & 0xff));
      out.push(row[i]);
      i = j;
    } else {
      // Literal run: find longest non-repeating sequence
      let k = j;
      while (k < row.length && k - i < 128) {
        if (k + 1 < row.length && row[k] === row[k + 1]) break;
        k++;
      }
      out.push(k - i - 1); // count-1
      for (let x = i; x < k; x++) out.push(row[x]);
      i = k;
    }
  }
  return Buffer.from(out);
}

export async function buildLogoPSD(logoBuf: Buffer): Promise<Buffer> {
  const { data, info } = await sharp(logoBuf)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const W = info.width, H = info.height;
  const CHANNELS = 4; // RGBA stored as R, G, B, A in PSD

  // Separate interleaved RGBA → 4 planar channels
  const planes = [
    Buffer.alloc(W * H), // R
    Buffer.alloc(W * H), // G
    Buffer.alloc(W * H), // B
    Buffer.alloc(W * H), // A
  ];
  for (let px = 0; px < W * H; px++) {
    planes[0][px] = data[px * 4];
    planes[1][px] = data[px * 4 + 1];
    planes[2][px] = data[px * 4 + 2];
    planes[3][px] = data[px * 4 + 3];
  }

  // RLE-encode each row of each channel; collect byte-count table + data
  const rowByteCounts: number[] = [];
  const rleChunks: Buffer[] = [];
  for (let c = 0; c < CHANNELS; c++) {
    for (let row = 0; row < H; row++) {
      const rowData = planes[c].subarray(row * W, row * W + W);
      const encoded = packBitsRow(rowData);
      rowByteCounts.push(encoded.length);
      rleChunks.push(encoded);
    }
  }

  // Row byte-count table (2 bytes per entry × channels × rows)
  const byteCountTable = Buffer.alloc(CHANNELS * H * 2);
  for (let i = 0; i < rowByteCounts.length; i++) {
    writeUInt16BE(byteCountTable, rowByteCounts[i], i * 2);
  }

  const parts: Buffer[] = [];

  // ── 1. File header (26 bytes) ──
  const header = Buffer.alloc(26);
  Buffer.from("8BPS").copy(header, 0);      // signature
  writeUInt16BE(header, 1, 4);              // version
  // reserved 6 bytes → already 0
  writeUInt16BE(header, CHANNELS, 12);      // channels (R,G,B,A)
  writeUInt32BE(header, H, 14);             // height
  writeUInt32BE(header, W, 18);             // width
  writeUInt16BE(header, 8, 22);             // bits per channel
  writeUInt16BE(header, 3, 24);             // color mode: RGB
  parts.push(header);

  // ── 2. Color mode data (4 bytes, length = 0) ──
  parts.push(Buffer.alloc(4));

  // ── 3. Image resources ──
  // Minimal: resolution info (72 dpi) resource block 0x03ED
  const resInfo = Buffer.alloc(16);
  writeUInt32BE(resInfo, 72 * 65536, 0);  // hRes as Fixed (72.0)
  writeUInt16BE(resInfo, 1, 4);           // hResUnit: pixels/inch
  writeUInt16BE(resInfo, 1, 6);           // widthUnit
  writeUInt32BE(resInfo, 72 * 65536, 8);  // vRes as Fixed (72.0)
  writeUInt16BE(resInfo, 1, 12);          // vResUnit: pixels/inch
  writeUInt16BE(resInfo, 1, 14);          // heightUnit

  // Resource block: "8BIM" + type + pascal string + length + data
  const resBlock = Buffer.alloc(4 + 2 + 2 + 4 + 16);
  Buffer.from("8BIM").copy(resBlock, 0);
  writeUInt16BE(resBlock, 0x03ED, 4);     // resource ID: resolution
  writeUInt16BE(resBlock, 0, 6);          // pascal string length = 0 (plus 1 pad)
  writeUInt32BE(resBlock, 16, 8);         // data length
  resInfo.copy(resBlock, 12);

  const imgResLength = Buffer.alloc(4);
  writeUInt32BE(imgResLength, resBlock.length, 0);
  parts.push(imgResLength);
  parts.push(resBlock);

  // ── 4. Layer and mask info (4 bytes, length = 0) ──
  parts.push(Buffer.alloc(4));

  // ── 5. Image data ──
  // Compression: 1 = PackBits RLE
  const compression = Buffer.alloc(2);
  writeUInt16BE(compression, 1, 0);
  parts.push(compression);
  parts.push(byteCountTable);
  for (const chunk of rleChunks) parts.push(chunk);

  return Buffer.concat(parts);
}

/* ── AI (Adobe Illustrator) ─────────────────────────────────────────────── */
// AI CS2+ uses PDF 1.4 as its native format.
// We produce a valid PDF with an AI-compatible header comment and
// XMP metadata so Illustrator recognises it as an AI file.

export async function buildLogoAI(
  logoBuf: Buffer,
  brandName: string,
): Promise<Buffer> {
  // Generate the PDF first (same 2-page layout)
  const pdfBuf = await buildLogoPDF(logoBuf, brandName);

  // Prepend the AI identification comment that Illustrator looks for.
  // Illustrator will open any PDF, but this marks it as "AI-native".
  const aiHeader = Buffer.from(
    `%!PS-Adobe-3.0\n%%Creator: Adobe Illustrator(R) / CreaCurve\n%%AI8_CreatorVersion: 16.0\n`,
    "utf-8",
  );

  // Inject after the %PDF line so the PDF remains valid
  const pdfStr = pdfBuf.toString("binary");
  const pdfMark = "%PDF-";
  const insertAt = pdfStr.indexOf(pdfMark);
  if (insertAt === -1) return pdfBuf; // fallback — return raw PDF

  const before = pdfBuf.subarray(0, insertAt);
  const after  = pdfBuf.subarray(insertAt);
  return Buffer.concat([before, aiHeader, after]);
}
