import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { PrintingShell } from '@/components/PrintingShell';
import { guides, getGuide } from '@/lib/printing/guides';
type Props = { params: Promise<{slug: string}> };
export function generateStaticParams() { return guides.map(g => ({slug:g.slug})); }
export async function generateMetadata({params}: Props): Promise<Metadata> { const {slug}=await params; const guide=getGuide(slug); if (!guide) return {}; return {title: guide.title, description: guide.description, alternates:{canonical:`/guides/${slug}`}, openGraph:{title:guide.title,description:guide.description,type:'article',url:`/guides/${slug}`}}; }
export default async function GuidePage({params}: Props) { const {slug}=await params; const guide=getGuide(slug); if (!guide) notFound(); const related=guides.filter(g=>g.slug!==slug).slice(0,3); const schema={'@context':'https://schema.org','@type':'Article',headline:guide.title,description:guide.description,author:{'@type':'Organization',name:'CreaCurve editorial team'},publisher:{'@type':'Organization',name:'CreaCurve',url:'https://creacurve.com'},mainEntityOfPage:`https://creacurve.com/guides/${slug}`}; return <PrintingShell><main className="mx-auto max-w-6xl px-5 py-14"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><Link href="/guides" className="text-sm font-semibold text-[#126659]">← All guides</Link><div className="mt-12 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#b36e34]">{guide.category} · {guide.readingMinutes} min read</p><h1 className="mt-4 text-4xl font-semibold leading-tight tracking-[-0.04em] md:text-6xl">{guide.title}</h1><p className="mt-6 text-xl leading-8 text-[#53605d]">{guide.description}</p><div className="mt-8 border-y border-[#d9dfd9] py-4 text-sm text-[#53605d]">By CreaCurve editorial team · Practical FDM printing guide</div><article className="mt-12 space-y-7 text-lg leading-9 text-[#303c39]">{guide.intro.map((p,i)=><p key={i}>{p}</p>)}{guide.sections.map((s,i)=><section key={s.heading} id={`section-${i}`} className="pt-5"><h2 className="mb-5 text-3xl font-semibold leading-tight tracking-tight text-[#182323]">{s.heading}</h2>{s.paragraphs.map((p,j)=><p key={j} className="mb-5">{p}</p>)}{s.bullets&&<ul className="my-6 list-disc space-y-2 pl-7">{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</section>)}<aside className="rounded-2xl bg-[#e4eee5] p-7"><h2 className="text-xl font-semibold text-[#126659]">Key takeaway</h2><p className="mt-3">{guide.takeaway}</p></aside></article><div className="mt-14 border-t border-[#d9dfd9] pt-7"><h2 className="text-2xl font-semibold">Keep learning</h2><div className="mt-5 grid gap-3">{related.map(g=><Link href={`/guides/${g.slug}`} key={g.slug} className="rounded-xl border border-[#d9dfd9] bg-white p-5 font-semibold hover:text-[#126659]">{g.title} →</Link>)}</div></div></div></main></PrintingShell>; }
